[project]
name = "paper-clean"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.2.0",
    "evaluate>=0.4.6",
    "langchain>=0.3.27",
    "langchain-deepseek>=0.1.4",
    "langchain-google-genai>=2.1.12",
    "langchain-openai>=0.3.35",
    "matplotlib>=3.10.7",
    "nltk>=3.9.2",
    "openai>=2.4.0",
    "pandas>=2.3.3",
    "pydantic>=2.12.2",
    "python-dotenv>=1.1.1",
    "ragas>=0.3.1",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "torch>=2.9.0",
    "transformers>=4.57.1",
]
